[package]
name = "auto-login-manager"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
strip = "symbols" 


[dependencies]
ipmb = "0.7.14"
# tokio = { version = "1.43.0", features = ["macros"] }

[build-dependencies]
embed-resource = "2.3"